---
exclude:
  - app/assets/stylesheets/awesome_translations/bootstrap.min.css
  - app/assets/stylesheets/awesome_translations/font-awesome/font-awesome.min.css

linters:
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  NestingDepth:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
    enabled: false
  ZeroUnit:
    enabled: false
